# Funding options for SelfHub
# Add your funding links here if you want to accept sponsorships

# github: [Sagargupta16]
# patreon: username
# ko_fi: username
# custom: ["https://paypal.me/username", "https://example.com/donate"]
